theme: p2pparis
baseURL: https://p2p.paris
title: Paris P2P (& Cryptography)

languageCode: en
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    params:
      locale: en_GB
      default_description: The Parisian community interested in P2P & Cryptography technologies
      404_desc: Page not found
      404_cta: Go to homepage      
    menu:
      main:
        - name: Events
          url: "/en/#events"
          weight: -100
        - name: About
          url: "/en/#about"
          weight: -90
        - name: Call for proposal
          url: "/en/#call-for-proposal"
          weight: -80
        - name: Meetup
          url: "#meetup"
          weight: -70
        - name: Discord
          url: "#discord"
          weight: -60
        - name: Github
          url: "#github"
          weight: -50
        - name: Contact
          url: "#contact"
          weight: -40
  fr:
    languageName: French
    params:
      locale: fr_FR
      default_description: La communauté parisienne intéressée par les technologies P2P et la Cryptographie
      404_desc: Page introuvable
      404_cta: Aller à la page d'accueil
      months:
        1: "janvier"
        2: "février"
        3: "mars"
        4: "avril"
        5: "mai"
        6: "juin"
        7: "juillet"
        8: "août"
        9: "septembre"
        10: "octobre"
        11: "novembre"
        12: "décembre"  
      months_short:
        1: "janv"
        2: "févr"
        3: "mars"
        4: "avr"
        5: "mai"
        6: "juin"
        7: "juil"
        8: "août"
        9: "sept"
        10: "oct"
        11: "nov"
        12: "déc"  
      days:
        0: "dimanche"
        1: "lundi"
        2: "mardi"
        3: "mercredi"
        4: "jeudi"
        5: "vendredi"
        6: "samedi"
      days_short:
        0: "dim"
        1: "lun"
        2: "mar"
        3: "mer"
        4: "jeu"
        5: "ven"
        6: "sam"
    menu:
      main:
        - name: Événements
          url: "/fr/#events"
          weight: -100
        - name: À propos
          url: "/fr/#about"
          weight: -90
        - name: Envoyez vos sujets
          url: "/fr/#call-for-proposal"
          weight: -80
        - name: Meetup
          url: "#meetup"
          weight: -70
        - name: Discord
          url: "#discord"
          weight: -60
        - name: Github
          url: "#github"
          weight: -50
        - name: Contact
          url: "#contact"
          weight: -50

params:
  default_featured_image: /img/paris_p2p_thumbnail.jpg
  googleAnalyticsId: UA-124224137-5
