theme: p2pparis
baseURL: https://p2p.paris
title: Paris P2P (& Cryptography)

languageCode: en
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    params:
      locale: en_GB
      default_description: The Parisian community interested in P2P & Cryptography technologies
      404_desc: Page not found
      404_cta: Go to homepage
    menu:
      main:
        - name: About
          url: "/en/#about"
          weight: -100
        - name: Call for proposal
          url: "/en/#call-for-proposal"
          weight: -90
        - name: Events
          url: "/en/#events"
          weight: -80
        - name: Meetup
          url: "/en/#meetup"
          weight: -70
        - name: Discord
          url: "/en/#discord"
          weight: -60
        - name: Github
          url: "/en/#github"
          weight: -50
        - name: Contact
          url: "/en/#contact"
          weight: -40
  fr:
    languageName: French
    params:
      locale: fr_FR
      default_description: La communauté parisienne intéréssée par les technologies P2P et la Cryptographie
      404_desc: Page introuvable
      404_cta: Aller à la page d'accueil
    menu:
      main:
        - name: À propos
          url: "/fr/#about"
          weight: -100
        - name: Envoyez vos sujets
          url: "/fr/#call-for-proposal"
          weight: -90
        - name: Évènements
          url: "/fr/#events"
          weight: -80
        - name: Meetup
          url: "/fr/#meetup"
          weight: -70
        - name: Discord
          url: "/fr/#discord"
          weight: -60
        - name: Github
          url: "/fr/#github"
          weight: -50
        - name: Contact
          url: "/fr/#contact"
          weight: -50

params:
  default_featured_image: /img/paris_p2p_thumbnail.jpg
  googleAnalyticsId: UA-124224137-5
