name: Trigger Netlify Build
on:
  schedule:
    # every day at 00.15AM
    # - cron: '15 0 * * *'
    - cron: '*/2 * * * *' # for testing
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.netlifyBuildUrl }}